### ISSUE TITLE
No longer works with ESPHome 2021.8 +

### ISSUE THREAD

**Issue by alej908** [a-lost-shadow/gosund-sw2#5]
When compiling I get the following error:

src/gosund_sw2_light.cpp: In member function 'virtual esphome::light::LightTraits esphome::gosund::GosundLight::get_traits()':
src/gosund_sw2_light.cpp:69:14: error: 'class esphome::light::LightTraits' has no member named 'set_supports_brightness'; did you mean 'get_supports_brightness'?
   69 |       traits.set_supports_brightness(true);
      |              ^~~~~~~~~~~~~~~~~~~~~~~
      |              get_supports_brightness

**Comment by cwalger** [comment]
replace the line:
			traits.set_supports_brightness(true);
with:
			traits.set_supported_color_modes({light::ColorMode::BRIGHTNESS});
